# Generated by Django 4.2.10 on 2024-02-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotVechicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.IntegerField(choices=[(1, '1st Slot'), (2, '2nd Slot'), (3, '3rd Slot')])),
                ('modified', models.DateTimeField()),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVechicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'SMALL'), (2, 'MEDIUM'), (3, 'LARGE')])),
                ('modified', models.DateTimeField()),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('spot_number', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_number', models.IntegerField(blank=True, choices=[(1, '1st Slot'), (2, '2nd Slot'), (3, '3rd Slot')], null=True)),
                ('Type_number', models.IntegerField(blank=True, choices=[(1, 'SMALL'), (2, 'MEDIUM'), (3, 'LARGE')], null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_app.entrydetails')),
            ],
        ),
    ]
