# Generated by Django 4.2.10 on 2024-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydetails',
            name='license_plate',
            field=models.CharField(max_length=15),
        ),
    ]
